apiVersion: v2
name: orion-ld
description: Chart holder for argo-cd

type: application
version: 0.1.0
appVersion: "1.0.1"

dependencies:
- name: orion-ld
  version: 1.0.2
  repository: file://./charts/orion-ld