{{- if .Values.broker.db.auth -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orion.fullname" . }}
  labels:
    {{ include "orion.labels" . | nindent 4 }}
type: Opaque
data:
  dbPassword: {{ .Values.broker.db.auth.password | b64enc }}
{{- end }}  